### PR TITLE
Adds Mac and XCB

### PR DESCRIPTION
**Pull request by Noitidart**
This my follow up to - https://github.com/carlin-q-scott/browser-media-keys/issues/17#issuecomment-229853852 - so this has the mac and even xcb support. I can't test it the mac one. And on my ubuntu the xcb is setting up correct (for play/pause) however I can't test it. My keyboard media keys won't work in my VMs for some reason.

The mac part is cleaning up but it is sooo slow I can't test things properly.

I didn't write up the `UseMkWin` method yet. I moved everything to a single ChromeWorker called `MainWorker`. Well it spawns a child worker of `PollWorker` when needed (only needed for mac). The Windows `RegisterHotKey` method is setup and working. The attach function is getting the `UseMkWin` value, so if you can populate that part of the `if` statement that would be awesome. If you haven't messed with creating hidden messaging window from worker let me know and I can take a stab at it. I did set one up in MouseControl initially but then removed it as I didn't need it.

I imported the `ostypes` submodule and used that so I didn't have to do any typing for ctypes. It would be awesome if you could continue to use this, and let me know or provide PRs for any types/functions/constants you need. A couple other people use this ostypes module as well.

### CODE REVIEW

**Comment by carlin-q-scott** [comment]
Looks like I need access to your repo for the submodule to download from your repo.

**Comment by Noitidart** [comment]
I got an email saying of a comment from you but I don't see it. I know we can't delete comments so I'm confused. But you were saying you don't have access to my submodule repos? comm and ostypes are both public:

https://github.com/Noitidart/ostypes

https://github.com/Noitidart/comm

**Comment by carlin-q-scott** [comment]
I deleted the comment because I figured out it was a travis-ci issue. I'm not sure why the AppVeyor tests failed because they pass for me.

**Comment by Noitidart** [comment]
Oh cool. By the way did you get a chance to test the XCB part? I don't have media keys so am eager to hear how that works out. I only implemented the "Play" key in this PR.

**Comment by carlin-q-scott** [comment]
I've only run the unit tests on Windows so far. I can check it out on Windows soon but currently have no way to validate Linux.

**Comment by Noitidart** [comment]
Hey @carlin-q-scott please run a `git pull` on `ostypes` submodue to update it. The linux module was dependent on a `core.os.**` and `core.firefox.**` variables which was specific to my code. I removed that dependency now.

**Comment by carlin-q-scott** [comment]
Thanks, I have updated the submodule in mac-support.

**Pull request merged**
