### PR TITLE
Add support for Google Play Music + all media key actions

### PR DESCRIPTION
**Pull request by davidjb**
Awesome addon, thanks!

This PR adds support for Google Play Music.  

In doing so, I noticed that the key values being emitted by my Firefox 39.0a2 install on Ubuntu 15.04 (Linux) weren't being picked up -- some key ids have even been changed in later versions of Gecko; so I've added support for those missing keys from https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key

Finally, my FF was initially erroring due to the ``require("firefoxHotkeys")`` line in hotkeyManager.js; so I adjusted this to be a relative path to the given file and this resolved the error.  

This is my first attempt at hacking on a FF addon, so if any of this is wrong, let me know.  Otherwise, working on my install of FF on Ubuntu.

### CODE REVIEW

**Comment by davidjb** [comment]
Thanks.  When you have a moment, could you please create a new release?

**Comment by carlin-q-scott** [comment]
Thanks for fixing all this stuff for the addon. I'm on FF 38.0 so I wouldn't have noticed these things for a while.

**Comment by carlin-q-scott** [comment]
I have pushed the new release (v5.1) to Mozilla. They will probably publish it on Wednesday based on the current review queue.

**Comment by davidjb** [comment]
Brilliant, thanks!

**Pull request merged**
