### PR TITLE
Implements jscSystemHotkey

### PR DESCRIPTION
**Pull request by Noitidart**
Does not have mkwin option as jscSystemHotkey doesn't work. But this fixes for all mac users and all *nix users. So the trade off is number of mkwin users for mac+non-dbus compat *nix. We can tell the mkwin users to keep old version of media keys, or we can either figure out why RegisterHotkey doesnt work for them or land mkwin to jscSystemHotkey.

Tested on Windows 10. Needs test on *nix and mac. Page @gmelikov, @X-Ryl669, @gaelfoppolo.

On Mac there is no "Media Key: Stop" so I set it to "F6" as the F6 key has nothing on it but is right next to the media keys per this image - http://xahlee.info/kbd/i/kb/Apple_iMac_Keyboard_A1242.jpg

Edit:
Update, most mac keyboards don't have "Media Key: Next" or "Media Key: Previous" either, they have "Rewind" and "Fast Forward" so it uses that.

### CODE REVIEW

**Comment by Noitidart** [comment]
Here is a XPI for testing for @gmelikov, @X-Ryl669, and @gaelfoppolo - [jid1-4GP7z3tkUd3Tzg@jetpack-0.7.8-patch-1.zip](https://github.com/carlin-q-scott/browser-media-keys/files/449467/jid1-4GP7z3tkUd3Tzg.jetpack-0.7.8-patch-1.zip)

Github wouldn't allow uploading XPI so just rename the .zip to .xpi and it's good to install.

**Comment by gmelikov** [comment]
@Noitidart it works, but i test with `xdotool key XF86AudioPrev`, because i don't have media keys.

Debian Jessie, Xfce, Firefox 48, Firefox ESR 46.

@Noitidart, could you add functionality to change hotkeys?

**Comment by Noitidart** [comment]
Awesome @gmelikov  thanks for the quick test! I could add it but I would have to design the options page for Carlin too. At that point I should probably be the author of the addon! Jk jk hahaha.

In the current state of the options pane I can't implement it too easily. I would have to get into XUL.

If you guys can find a nice HTML template you like I can hook it up in another PR, just for experimentation.

**Comment by X-Ryl669** [comment]
It does not work for me. Restarted firefox, installed the xpi via about:debugging, it appears as "Media Keys" in about:addons. It does not seem to react to the media keys at all (none of them).

**Comment by Noitidart** [comment]
@X-Ryl669 shoot ok I'll pull up my mac vm and test it there, it should be pretty obvious. I didn't mess with the internals of jscSystemHotkey. Will get back to you in a bit.

**Comment by carlin-q-scott** [comment]
Is it ok if I merge this with mac-support instead of master? I could then release different xpi's for Windows and Mac/Linux to handle the precarious state of mkwin.

**Comment by Noitidart** [comment]
@X-Ryl669 please try this XPI - 
[jid1-4GP7z3tkUd3Tzg@jetpack-0.7.8-pacth-1-macfix.zip](https://github.com/carlin-q-scott/browser-media-keys/files/449559/jid1-4GP7z3tkUd3Tzg.jetpack-0.7.8-pacth-1-macfix.zip)

@carlin-q-scott that's a cool idea! Or you could make a PR to jscSystemHotkey with mkwin support. That would be cooler!

**Comment by carlin-q-scott** [comment]
Does this PR address #17, #33, #35 and #65? Also I assume you handled #29 already when you created those sub modules.

**Comment by carlin-q-scott** [comment]
Ok, I can do a PR for jscSystemHotkey and get it all over with :)

**Comment by Noitidart** [comment]
That would be awesome Carlin!

Yep it closes all of those :)

Let's just wait to hear back on the mac test by X-Ryl. My mac vm is soooo slow its unbearable.

**Comment by Noitidart** [comment]
@X-Ryl669 ok I fixed it, it was me being silly, when I copied files I forgot to change the path. Thanks for that! Please try this XPI - [jid1-4GP7z3tkUd3Tzg@jetpack-0.7.8-patch-1-macfixed.zip](https://github.com/carlin-q-scott/browser-media-keys/files/449615/jid1-4GP7z3tkUd3Tzg.jetpack-0.7.8-patch-1-macfixed.zip)

**Comment by X-Ryl669** [comment]
Ok, last version react to shift+space (emulate play/pause button) but does not react to music keys (it still launch iTunes)
I've tested this after restarting Firefox (else it says this: `Failed to install hotkey event handler for OSStatus of "4294957430" / "-9866"`)

**Comment by Noitidart** [comment]
@X-Ryl669 that is very odd, this one does not have the code in there to react to Shift + Space. The last debug version I sent you has that though. Please uninstall that then restart firefox then try installing this. 

Reason for restart - during the dev build I sent you last week, I had issues in there which probably prevents multiple addons from registering hotkeys. The latest should not have issues with multiple addons subscribing to hotkey events.

**Comment by X-Ryl669** [comment]
Well, my fault. I tried the Shift+ Space combination with the music tab opened. It caught the 'space' shortcut, and I thought it worked. Anyway, I don't have the extension from last week installed anymore (since last week or so ;-). 
So, actually, it does not work at all for me. Do you want the browser console output ?

**Comment by Noitidart** [comment]
Thanks @X-Ryl669 yes please, could you pastebin that, would you have time to jump onto IRC?

**Comment by X-Ryl669** [comment]
Ok, I'm ready.

**Comment by Noitidart** [comment]
Lots thanks to @X-Ryl669 for the in depth testing! Mac is now fixed:

@carlin-q-scott  I had to update jscSystemHotkey submodule, i hope it doesnt break anything.

**Comment by Noitidart** [comment]
@reuben and @mstange I think you guys might be interested to see this project as you guys kind of pioneered it in firefox with the dylibs: https://github.com/reuben/mediakeysappleremoteyoutube

**Comment by carlin-q-scott** [comment]
I haven't had the necessary time to dig into this yet so I merged it with mac-support and am going to release it for mac and linux

**Pull request closed without merging**
