### PR TITLE
Re-attach Linux hotkey manager on activating a tab

### LINKED ISSUE #10: Restarting listening for Linux DBus signals on Firefox regaining focus
As mentioned in #7, there's a caveat for Linux DBus support that another DBus application (eg Rhythmbox) opens after Media Keys starts listening to DBus, that application takes over listening and Media Keys won't get any signals until that application exits. 

Normally, other DBus applications (the ones I've seen, like Rhythmbox) take DBus precedence back (eg they restart listening) if/when they re-gain focus.  So, what Media Keys should do is restart listening (eg ``DetachEventListeners`` and ``AttachEventListeners`` in the DBus module) upon Firefox regaining focus to one of its windows.  

This isn't a huge issue for me as quitting the other application is just as easy to do (or disable/re-enable Media Keys), but it's worth mentioning in case a fix is simple.  It might be too much overhead to worry about.

### PR DESCRIPTION
**Pull request by davidjb**
This fixes #10.

### CODE REVIEW

**Comment by davidjb** [comment]
This is based off the code from #9 so that's best merged first to make the changes here clear.

**Comment by carlin-q-scott** [comment]
The code seems a bit to reactive to me. If someone is just flipping back and forth between media tabs then we probably don't want to reset the dbus hotkeys. I also question the else piece as I think that piece of code should always run.

**Comment by davidjb** [comment]
You're right about the ``else`` condition; I've adjusted the PR accordingly.

As for changing tabs, the issue is not knowing whether you need to start re-listening again to the DBus messages.    I've adjusted the PR to only re-grab the keys on tab activation; and only fully attach if the dbus proxy object doesn't exist (eg was detached).  This follows what Rhythmbox does (https://git.gnome.org/browse/rhythmbox/tree/plugins/mmkeys/rb-mmkeys-plugin.c#n165) on re-gaining focus, so that's seemingly the best one can do.  Fwiw, there's a ``g_signal_handler_is_connected`` function available in the GObject API, but it's only checking whether the handler is connected, not whether it'll be the first receiver of a signal.

I've also jshint'd the linux dbus code.  The unused ctypes code is now commented out; I left it in place in case its needed again.  It can be removed if necessary, but having it still present makes it easier than re-looking up some of those complicated function definitions and enums if/when they're needed again.

**Comment by carlin-q-scott** [comment]
Looks good. Thanks for making those adjustments and I'm glad you left the extra code there in case we need it later. 

We probably cannot be expected to do a better job than Rythmbox :).

**Comment by davidjb** [comment]
No problem, thanks for merging & again for writing the original code (it's really well structured and easily extendible).

I figure with the commented code, some other lucky person who tries js-ctypes with DBus will hit upon the code and feel they've struck gold.

As for us out-doing Rhythmbox, well I was thinking since Rhyhmbox is a GNOME project, and glib and DBus are GNOME projects..it's *probably* going to be about as good as it gets!

**Comment by carlin-q-scott** [comment]
Thanks, I'm glad to hear that. I try my best to write maintainable code so it's great to hear that it achieved that for someone other than myself.

lol @ striking gold.

**Pull request merged**
